version: 2

builds:
  - id: kubeconfgen
    main: ./cmd/kubeconfgen/
    binary: kubeconfgen
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - linux_amd64_v1
      - darwin_amd64_v1
      - windows_amd64_v1

archives:
  - id: default
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
